# Generated by Django 3.2.10 on 2021-12-21 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task_Manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='user',
        ),
    ]
