# Generated by Django 3.2.10 on 2021-12-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task_Manager', '0002_remove_tasks_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='done',
            field=models.BooleanField(blank=True, default=False, verbose_name='Done'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='text',
            field=models.CharField(blank=True, max_length=128, verbose_name='Text'),
        ),
    ]
