# Generated by Django 3.2.10 on 2021-12-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task_Manager', '0007_alter_tasks_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='title',
            field=models.CharField(blank=True, max_length=128, verbose_name='Title'),
        ),
    ]
